spring.application.name=proyecto-crud
spring.datasource.url=jdbc:mysql://localhost:3306/escuela
spring.datasource.username=root
spring.datasource.password=SumoPerroHormiga2901

spring.jpa.show-sql=false

